/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license.
Authors: Bryan Ehrlich
-/
import Mathlib.Algebra.Jordan.Basic
import Mathlib.Algebra.Module.Defs
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Ring.Basic

/-!
# Albert's power-associativity theorem for commutative Jordan algebras

A **Jordan algebra** is a commutative (generally non-associative) algebra satisfying the
Jordan identity `(x * y) * (x * x) = x * (y * (x * x))`.  Associativity fails in general, so there is no a priori reason for the different bracketings of
a repeated product to agree, and an expression like `x ^ n` has no a priori meaning.

Albert's power-associativity theorem (1948) says that it does: the powers of a single element
associate, equivalently they multiply additively.  (Not "the subalgebra generated by one
element": the hypotheses below do not make the real module structure interact with the
multiplication, so no real subalgebra is in play - see the note on `[Module ℝ J]`.)  This file
states that theorem.

Everything the statement mentions is defined here from Mathlib: `IsCommJordan` is Mathlib's
Jordan identity typeclass, and `jpow` is three lines of recursion.
-/

namespace AlbertPowerAssoc

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J] [Module ℝ J]

/-- **Powers of a single element**, indexed from one so that no multiplicative unit is
assumed: `jpow x n` is the element written `x ^ (n+1)` in ordinary notation, defined by
`jpow x 0 = x` and `jpow x (n+1) = x * jpow x n`.

The indexing shift matters here. A Jordan algebra need not be unital, so `x ^ 0 = 1` is not
available, and the statement below is deliberately phrased so that it never mentions a unit. -/
def jpow (x : J) : ℕ → J
  | 0 => x
  | (n + 1) => x * jpow x n

/-- **Albert's power-associativity theorem.**  In a commutative Jordan ring carrying an
ℝ-module structure, the powers of a single element multiply the way powers ought to:

`x^(m+1) * x^(n+1) = x^(m+n+2)`.

This is the theorem that makes the products of powers of a single element associate, and it
is what any spectral theory for Jordan algebras is built on. It specializes to commutative
Jordan rings the torsion-free power-associativity criterion of A. A. Albert, *Power-associative
rings*, Trans. Amer. Math. Soc. 64 (1948) 552-593.

What is and is not assumed. `IsCommJordan` is commutativity plus the Jordan identity
`(x * y) * (x * x) = x * (y * (x * x))`. Beyond that: no unit, no finite dimension, no formal
reality, no inner product, no positivity, no idempotents.

**On `[Module ℝ J]`.** It is not Mathlib's recipe for a real Jordan algebra, which additionally
asks for `SMulCommClass ℝ J J` and `IsScalarTower ℝ J J`; without those the scalar action need
not interact with the multiplication, so this is not a statement about the real subalgebra
generated by `x`. The proof uses the module structure only to cancel a nonzero natural multiple
(`(N+3) • c = 0 ⟹ c = 0`), that is, for additive torsion-freeness. The hypothesis is therefore
stronger than the argument needs. -/
theorem jpow_mul_jpow (x : J) (m n : ℕ) :
    jpow x m * jpow x n = jpow x (m + n + 1) := sorry

end AlbertPowerAssoc
