/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license.
Authors: Bryan Ehrlich
-/
import Mathlib.Algebra.Jordan.Basic
import Mathlib.Algebra.Module.Defs
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Ring.Basic

/-!
# Albert's power-associativity theorem for commutative Jordan algebras

A **Jordan algebra** is a commutative (generally non-associative) algebra satisfying the
Jordan identity `(x * y) * (x * x) = x * (y * (x * x))`.  Associativity fails in general, so
`x * (x * x)` and `(x * x) * x` have no a priori reason to agree, and an expression like
`x ^ 5` has no a priori meaning.

Albert's theorem (1946) says that it does: the subalgebra generated by a single element is
associative, equivalently the powers of one element multiply additively.  This file states
that theorem.

Everything the statement mentions is defined here from Mathlib: `IsCommJordan` is Mathlib's
Jordan identity typeclass, and `jpow` is three lines of recursion.
-/

namespace AlbertPowerAssoc

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J] [Module ℝ J]

/-- **Powers of a single element**, indexed from one so that no multiplicative unit is
assumed: `jpow x n` is the element written `x ^ (n+1)` in ordinary notation, defined by
`jpow x 0 = x` and `jpow x (n+1) = x * jpow x n`.

The indexing shift matters here. A Jordan algebra need not be unital, so `x ^ 0 = 1` is not
available, and the statement below is deliberately phrased so that it never mentions a unit. -/
def jpow (x : J) : ℕ → J
  | 0 => x
  | (n + 1) => x * jpow x n

/-- **Albert's power-associativity theorem.**  In a commutative Jordan algebra over the reals,
the powers of a single element multiply the way powers ought to:

`x^(m+1) * x^(n+1) = x^(m+n+2)`.

This is the theorem that makes "the subalgebra generated by one element is associative"
true, and it is what any spectral theory for Jordan algebras is built on. It is due to
A. A. Albert (1946).

The hypotheses are the weakest they can be. `IsCommJordan` is commutativity plus the Jordan
identity `(x * y) * (x * x) = x * (y * (x * x))`, and that together with the real scalars is
all that is used: no unit, no finite dimension, no formal reality, no inner product, no
positivity, no idempotents. -/
theorem jpow_mul_jpow (x : J) (m n : ℕ) :
    jpow x m * jpow x n = jpow x (m + n + 1) := sorry

end AlbertPowerAssoc
