/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license.
Authors: Bryan Ehrlich
-/
import Mathlib.Algebra.Jordan.Basic
import Mathlib.Algebra.Module.Defs
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Ring.Basic
import RadicalRelativity.EJA.PowerAssoc

/-!
# Solution: Albert's power-associativity theorem

Repeats the definitions of `AlbertChallenge.lean` verbatim and discharges the theorem from
`RadicalRelativity.EJA.jpow_mul_jpow`.  The two `jpow` definitions are the same recursion, so
the bridge is a one-line induction.
-/

namespace AlbertPowerAssoc

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J] [Module ℝ J]

/-- **Powers of a single element**, indexed from one so that no multiplicative unit is
assumed: `jpow x n` is the element written `x ^ (n+1)` in ordinary notation, defined by
`jpow x 0 = x` and `jpow x (n+1) = x * jpow x n`.

The indexing shift matters here. A Jordan algebra need not be unital, so `x ^ 0 = 1` is not
available, and the statement below is deliberately phrased so that it never mentions a unit. -/
def jpow (x : J) : ℕ → J
  | 0 => x
  | (n + 1) => x * jpow x n

/-- **Albert's power-associativity theorem.**  In a commutative Jordan algebra over the reals,
the powers of a single element multiply the way powers ought to:

`x^(m+1) * x^(n+1) = x^(m+n+2)`.

This is the theorem that makes "the subalgebra generated by one element is associative"
true, and it is what any spectral theory for Jordan algebras is built on. It is due to
A. A. Albert (1946).

The hypotheses are the weakest they can be. `IsCommJordan` is commutativity plus the Jordan
identity `(x * y) * (x * x) = x * (y * (x * x))`, and that together with the real scalars is
all that is used: no unit, no finite dimension, no formal reality, no inner product, no
positivity, no idempotents. -/
theorem jpow_mul_jpow (x : J) (m n : ℕ) :
    jpow x m * jpow x n = jpow x (m + n + 1) := by
  have h : ∀ (y : J) (k : ℕ), jpow y k = RadicalRelativity.EJA.jpow y k := by
    intro y k
    induction k with
    | zero => rfl
    | succ k ih => simp only [jpow, RadicalRelativity.EJA.jpow, ih]
  simp only [h]
  exact RadicalRelativity.EJA.jpow_mul_jpow x m n

end AlbertPowerAssoc
