/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license.
Authors: Bryan Ehrlich
-/
import RadicalRelativity.EJA.PowerAssoc
import Mathlib.LinearAlgebra.Dimension.Finite

set_option linter.style.longLine false

/-!
# The subalgebra generated by one element is associative

**ARC-9 block 9.11, 2026-08-12.**

This is Albert's theorem in the form it is usually *stated* — `EJA/PowerAssoc.lean` proves the
form it is usually *proved* in, the power law `x^{m+1} ∘ x^{n+1} = x^{m+n+2}`. The two are not
the same statement: the power law is about products of powers, and this is about products of
arbitrary `ℝ`-combinations of powers.

`jspan x` is the `ℝ`-span of `{x, x², x³, …}`. The results:

* `mul_mem_jspan` — it is closed under the Jordan product, so it is a subalgebra;
* `jspan_assoc` — **the product is associative on it**.

Both come from `jpow_mul_jpow` by span induction and nothing else. `jspan_assoc` needs three
nested inductions because associativity is trilinear, which is the only reason this file is
longer than its content.

## Why it is worth stating separately

The route to **(E1)**, the Jordan spectral theorem, runs through `ℝ[x]`: one shows it is a
finite-dimensional associative commutative real algebra, that formal reality makes it reduced
(`EJA/FormallyReal.lean`), and hence that it is `ℝ^k` — which produces the orthogonal
idempotents that `EJA/Frame.lean` then consumes. **`jspan_assoc` is the first of those four
steps.** The remaining three — finite-dimensionality of `jspan x`, reducedness in the form the
classification wants, and the classification itself — are not built.

★ `jspan x` is a `Submodule`, not a `NonUnitalSubalgebra`: bundling it would need the ambient
`NonUnitalNonAssocCommRing` to carry an algebra structure over `ℝ`, which this unit-free
development deliberately does not assume. The two theorems below say exactly what a bundled
version would, without the bundling.
-/

namespace RadicalRelativity.EJA

section Subalgebra

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J] [Module ℝ J]
  [IsScalarTower ℝ J J]

/-- The `ℝ`-span of the powers of `x`: the subalgebra generated by `x`. -/
def jspan (x : J) : Submodule ℝ J := Submodule.span ℝ (Set.range (jpow x))

omit [IsCommJordan J] [IsScalarTower ℝ J J] in
theorem jpow_mem_jspan (x : J) (n : ℕ) : jpow x n ∈ jspan x :=
  Submodule.subset_span ⟨n, rfl⟩

omit [IsCommJordan J] [IsScalarTower ℝ J J] in
theorem self_mem_jspan (x : J) : x ∈ jspan x := by
  simpa using jpow_mem_jspan x 0

/-- `jspan x` is closed under the Jordan product. -/
theorem mul_mem_jspan {x a b : J} (ha : a ∈ jspan x) (hb : b ∈ jspan x) : a * b ∈ jspan x := by
  have key : ∀ n : ℕ, ∀ c ∈ jspan x, jpow x n * c ∈ jspan x := by
    intro n c hc
    induction hc using Submodule.span_induction with
    | mem y hy =>
        obtain ⟨m, rfl⟩ := hy
        rw [jpow_mul_jpow]
        exact jpow_mem_jspan x _
    | zero => rw [mul_zero]; exact Submodule.zero_mem _
    | add u v _ _ hu hv => rw [mul_add]; exact Submodule.add_mem _ hu hv
    | smul r u _ hu => rw [mul_smul_comm']; exact Submodule.smul_mem _ r hu
  induction ha using Submodule.span_induction with
  | mem y hy => obtain ⟨n, rfl⟩ := hy; exact key n b hb
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add u v _ _ hu hv => rw [add_mul]; exact Submodule.add_mem _ hu hv
  | smul r u _ hu => rw [smul_mul_assoc]; exact Submodule.smul_mem _ r hu

/-- **Albert's theorem, classical form: the subalgebra generated by one element is
associative.** -/
theorem jspan_assoc {x a b c : J} (ha : a ∈ jspan x) (hb : b ∈ jspan x) (hc : c ∈ jspan x) :
    (a * b) * c = a * (b * c) := by
  have h3 : ∀ i j : ℕ, ∀ z ∈ jspan x, (jpow x i * jpow x j) * z = jpow x i * (jpow x j * z) := by
    intro i j z hz
    induction hz using Submodule.span_induction with
    | mem y hy =>
        obtain ⟨k, rfl⟩ := hy
        rw [jpow_mul_jpow, jpow_mul_jpow, jpow_mul_jpow, jpow_mul_jpow]
        congr 1
        omega
    | zero => rw [mul_zero, mul_zero, mul_zero]
    | add u v _ _ hu hv => rw [mul_add, mul_add, mul_add, hu, hv]
    | smul r u _ hu => rw [mul_smul_comm', mul_smul_comm', mul_smul_comm', hu]
  have h2 : ∀ i : ℕ, ∀ y ∈ jspan x, ∀ z ∈ jspan x,
      (jpow x i * y) * z = jpow x i * (y * z) := by
    intro i y hy z hz
    induction hy using Submodule.span_induction with
    | mem w hw => obtain ⟨j, rfl⟩ := hw; exact h3 i j z hz
    | zero => rw [mul_zero, zero_mul, mul_zero]
    | add u v _ _ hu hv => rw [mul_add, add_mul, hu, hv, ← mul_add, ← add_mul]
    | smul r u _ hu => simp only [mul_smul_comm', smul_mul_assoc]; rw [hu]
  induction ha using Submodule.span_induction with
  | mem w hw => obtain ⟨i, rfl⟩ := hw; exact h2 i b hb c hc
  | zero => rw [zero_mul, zero_mul, zero_mul]
  | add u v _ _ hu hv => rw [add_mul, add_mul, add_mul, hu, hv]
  | smul r u _ hu => rw [smul_mul_assoc, smul_mul_assoc, smul_mul_assoc, hu]

/-! ### The finite-dimensional entry point

★ **Both results below are linear algebra, not Jordan theory**, and their `omit` lines prove
it: neither uses `IsCommJordan`. They are recorded here because they are step 1 of the route
to (E1) and because it is worth being explicit that step 1 is free — all the difficulty in
the spectral theorem is downstream, in turning an annihilating relation into idempotents. -/

section Finite

variable [Module.Finite ℝ J]

omit [IsCommJordan J] [IsScalarTower ℝ J J] in
/-- **A nontrivial annihilating relation among the powers.** In finite dimension the powers of
`x` cannot be independent, so some nonzero real combination of `x, x², …, x^{N+1}` vanishes —
the existence half of a minimal polynomial *with zero constant term*, which is the right shape
for a unit-free setting.

★ No Jordan input: this is "an over-long family in a finite-dimensional space is dependent". -/
theorem exists_jpow_relation (x : J) :
    ∃ (n : ℕ) (c : Fin n → ℝ), (∃ i, c i ≠ 0) ∧ ∑ i, c i • jpow x i = 0 := by
  have hnot : ¬ LinearIndependent ℝ (fun i : Fin (Module.finrank ℝ J + 1) => jpow x i) := by
    intro h
    have hle := h.fintype_card_le_finrank
    simp only [Fintype.card_fin] at hle
    omega
  obtain ⟨c, hsum, i, hi⟩ := Fintype.not_linearIndependent_iff.mp hnot
  exact ⟨_, c, ⟨i, hi⟩, hsum⟩

omit [IsCommJordan J] [IsScalarTower ℝ J J] in
/-- `jspan x` is finite-dimensional. Immediate — it is a submodule of a finite-dimensional
space — and recorded only so that the (E1) route can cite it. -/
instance jspan_finite (x : J) : Module.Finite ℝ (jspan x) :=
  Module.Finite.of_injective (jspan x).subtype (jspan x).injective_subtype

end Finite

end Subalgebra

end RadicalRelativity.EJA
